# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Worth Reading
tagline:          'Articles, videos and other content I find interesting.'
description:      'Weekly collection of articles, videos and other content I find interesting. Made by <a href="https://twitter.com/mihneadb" target="_blank">@mihneadb</a>.'
url:              http://www.worthreading.it
baseurl:          /

author:
  name:           'Mihnea Dobrescu-Balaur'
  url:            https://www.mihneadb.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mihneadb/worthreading
